language: python
python:
  - "2.7"
# command to run tests

install:
  - pip install git+git://github.com/minichate/nose-memory-grinder
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=Calculator --with-timer --with-nose-memory-grind
  

